{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "keycloak.createConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: keycloak
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  keycloak.conf: |-
    {{- .Values.configuration | nindent 4 }}
{{- end }}

---
{{/*
Dynamic ConfigMap template for multiple SPI JARs
*/}}

{{- if .Values.librariesSpi.enabled }}
{{- $namespace := include "common.names.namespace" . }}
{{- $commonLabels := .Values.commonLabels }}
{{- $commonAnnotations := .Values.commonAnnotations }}
{{- $context := $ }}

{{- range .Values.librariesSpi.jars }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $commonLabels "context" $context ) | nindent 4 }}
    app.kubernetes.io/component: keycloak
  {{- if $commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $commonAnnotations "context" $context ) | nindent 4 }}
  {{- end }}
binaryData:
  {{ .name }}.jar: {{ $.Files.Get .path | b64enc }}
{{- end }}
{{- end }}
